---
title: "Make_event_files"
author: "Wanjia Guo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
library(tidyverse)
library(fs)
theme_set(theme_minimal(15))
```

```{r setup, include=FALSE}

converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub))
}

# Loading behavioral data
sub_dir = dir_ls(here::here("csv_files/behavior/"),  type = "directory")
scan_timing = map(sub_dir, dir_ls, regexp = '(.*)_scan(\\d?\\d)_timing_.*') %>% unlist()
timing_batch = map_dfr(scan_timing, converting_read)

```

```{r}
event_files = timing_batch %>% 
  #  calculate TR. as.integer's default is flooring.
  mutate(TR = as.integer(design_onset)) %>% 
  # Remove _ from npic
  separate(npic, 
           into ='n_pic', 
           sep = '_', 
           extra = 'drop', 
           remove = FALSE) %>% 
  # Getting name for pair and route
    separate(condition, 
           into =c('pair', 'route'), 
           sep = '/', 
           extra = 'drop', 
           remove = FALSE) %>% 
  # Getting trial type (valid vs. invalid; catch vs. non-catch)
    separate(route, 
           into =c('route', 'valid', 'trial_type'), 
           extra = 'drop', 
           sep = ',',
           remove = FALSE) %>%
  mutate(pair = str_sub(pair, start = 3),
         route = stringr::str_extract(route, "[a-z]+"),
         catch = stringr::str_extract(trial_type, "[0-1]+")) %>% 
  select(-c(trial_type, npic, condition)) %>% 
  # Getting segment
  mutate(int_pic = as.integer(n_pic)) %>% 
  mutate(segment = ifelse(is.na(int_pic), n_pic,
                    ifelse(int_pic <= 25, 'same',
                            ifelse(int_pic >= 76, 'non-overlapping',
                                   'overlapping')))) %>% 
  select(-int_pic) %>% 
  mutate(valid = as.integer((valid)),
         catch = as.integer(catch))
```

# non-catch trials with only images displaying time points

```{r}
event = event_files %>% filter(catch == 0) %>% 
  filter(segment == 'same' | segment == 'overlapping' | segment == 'non-overlapping') %>% 
  mutate(round = as.integer(round)) %>%
  group_by(sub, round, trial, pair, route, segment, valid, catch) %>% 
  summarize(TR = min(design_onset) %>% round() %>% as.integer()) %>%
  mutate(end_TR = ifelse((segment == 'same' | segment == 'non-overlapping'), TR+5, TR+11)) %>% 
  mutate(behav_TR = map2(TR, end_TR, ~ seq(from = .x, to = .y))) %>%
  unnest(behav_TR) %>% 
  mutate(within_trial_TR = behav_TR - TR) %>% 
  mutate(within_trial_TR = ifelse(segment == 'overlapping',
         within_trial_TR+7, 
         ifelse(segment == 'non-overlapping', 
                within_trial_TR + 19,
                within_trial_TR + 1)
         ),
         odd.even = ifelse(round %% 2 == 0, 'even', 'odd')) %>% 
  select(-c(TR, end_TR, catch))

```

