---
title: "Preliminary fMRI data"
author: "Wanjia Guo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width=20, fig.height=16) 

library(tidyverse)
library(fs)
library(ggplot2)
theme_set(theme_minimal(18))

library(ezPurrr)

cbPalette <- c("#CC79A7","#009E73","#0072B2","#E69F00","#56B4E9","#F0E442","#999999","#D55E00")
#pink, green, blue, yellow
```


```{r}
calculate_mean = function(sample){
  
  summary = sample %>% 
    summarise(across_pair = mean(across_pair),
              within_pair = mean(within_pair),
              within_item = mean(within_item))
  
  summary
  
}
```



```{r reading in data}
rois_names = c('ca23dg-body', 'ca1-body', 
               'ca23dg', 'ca1',
               'angular_gyrus', 'evc', 
               'hippocampus', 'ppa')

rois_names = c('ca23dg-body', 'ca1-body')

rdata_dir = here::here("./csv_files/RDS")

roi_dir = dir_ls(here::here("csv_files/RDS/"),  type = "directory")
processed_sub_list = map(roi_dir, dir_ls) %>% unlist() %>% 
  map_chr(~gsub('.*/sub-([0-9]+)_.*','\\1', .x)) %>% 
  unlist() %>% 
  unique()

remove('huge_df')

for (roi in rois_names){
  for (sub in processed_sub_list){
    curr_df = readRDS(file.path(rdata_dir, roi, paste0('sub-', sub, '_', roi, '.RDS')))
    
    curr_df = curr_df %>% 
      mutate(data = output) %>% 
      unnest(cols = output) %>% 
      select(-data)
    
    curr_df$sub = sub
    curr_df$roi = roi
    if (exists('huge_df')){
      huge_df = rbind(huge_df, curr_df)
    } else(
      huge_df = curr_df
    )
  }
}
```

## n = `r length(processed_sub_list)`

```{r plotting function}
making_2_plots <- function(df){
  
  tmp = df %>% mutate(wp_ap = within_pair - across_pair,
         segment = factor(segment, levels = c('same', 'overlapping', 'non-overlapping'))) 

  tmp$roi =  factor(tmp$roi,
                levels = c('ca23dg-body', 'ca23dg',
                           'ca1-body', 'ca1',
                           'hippocampus', 'ppa',
                           'angular_gyrus', 'evc'))
  
  tmp_sub = tmp %>% group_by(segment, valid, within_trial_TR, roi) %>% 
    summarise(across_pair_m = mean(across_pair),
              across_pair_se = sd(across_pair)/sqrt(n()),
              within_pair_m = mean(within_pair),
              within_pair_se = sd(within_pair)/sqrt(n()),
              within_item_m = mean(within_item),
              within_item_se = sd(within_item)/sqrt(n()),
              wp_ap_m = mean(wp_ap),
              wp_ap_se = sd(wp_ap)/sqrt(n())
              )

  tmp_sub$roi =  factor(tmp_sub$roi,
                           levels = c('ca23dg-body', 'ca23dg',
                                      'ca1-body', 'ca1',
                                      'hippocampus', 'ppa',
                                      'angular_gyrus', 'evc'))

  p1 = tmp_sub %>% ggplot(aes(x = within_trial_TR, y = wp_ap_m, color = valid)) +
    geom_vline(xintercept=6) +
    geom_vline(xintercept=18) +
    geom_ribbon(aes(ymin = wp_ap_m-wp_ap_se, 
                    ymax = wp_ap_m+wp_ap_se,
                    fill = valid),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'within_pair - across_pair',
         x = 'within trial timepoint') + 
    theme(legend.position="bottom",
          legend.title = element_blank()) + 
    facet_wrap(~roi, ncol = 2, scales = 'free_y')
  
    tmp2 = tmp %>% group_by(sub, segment, valid, roi) %>% 
      summarise(wp_ap_m = mean(wp_ap),
                wp_ap_se = sd(wp_ap)/sqrt(n())
                )
    
    p2 = tmp2 %>% group_by(segment, valid, roi) %>% 
      summarise(m = mean(wp_ap_m),
                se = sd(wp_ap_m)/sqrt(n()),
                n = n()
                ) %>% 
      ggplot(aes(x = segment, y = m, fill = valid)) +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
      geom_point(data = tmp2, aes(x = segment, y = wp_ap_m, color = valid, group = valid), 
                  position=position_jitterdodge(
                    jitter.width = 0.2,
                    dodge.width = 0.75)) + 
      labs(y = 'within_pair - across_pair')+ 
      theme(legend.position="bottom",
            legend.title = element_blank()) + 
      facet_wrap(~roi, ncol = 2, scales = 'free_y')
    
    list(p1, p2)
}


```

### All subjects together

```{r}

all_sub_df = huge_df %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(all_sub_df)

output[[1]]
output[[2]]

```

### sub-09 + pair2_north and sub-10 + pair3_west

```{r}

late_df = huge_df %>% filter((sub == '09' & pair == 'pair2_north') |
                               (sub == '10' & pair == 'pair3_west')) %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(late_df)

output[[1]]
output[[2]]
```

### everyone else

```{r}
early_df = huge_df %>% filter(!(sub == '09' & pair == 'pair2_north')) %>% 
  filter(!(sub == '10' & pair == 'pair3_west')) %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(early_df)

output[[1]]
output[[2]]
```

### each pair of routes

pair1 east: 

```{r}
pair1_df = huge_df %>% filter(pair == 'pair1_east') %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(pair1_df)

output[[1]]
output[[2]]
```

pair3 west:

```{r}
pair3_df = huge_df %>% filter(pair == 'pair3_west') %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(pair3_df)

output[[1]]
output[[2]]
```

pair2 north:

```{r}
pair2_df = huge_df %>% filter(pair == 'pair2_north') %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(pair2_df)

output[[1]]
output[[2]]
```

pair4 south

```{r}
pair4_df = huge_df %>% filter(pair == 'pair4_south') %>% 
  group_by(segment, valid, within_trial_TR, roi, sub) %>% 
  nest() %>% 
  broadcast(calculate_mean) %>%
  select(-data) %>% 
  unnest(cols = output)

output = making_2_plots(pair4_df)

output[[1]]
output[[2]]
```


```{r Talk figures 1, eval=FALSE, include=FALSE}
tmp_sub %>% 
  filter(roi %in% c('ca23dg-body', 'ppa', 'evc') &
         valid == 'valid') %>%
  ggplot(aes(x = within_trial_TR, y = wp_ap_m, color = roi)) +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey")+
  geom_vline(xintercept=6, linetype="dashed", color = "darkgrey") +
  geom_vline(xintercept=18, linetype="dashed", color = "darkgrey") +
  geom_ribbon(aes(ymin = wp_ap_m-wp_ap_se, 
                  ymax = wp_ap_m+wp_ap_se,
                  fill = roi),
              alpha = 0.2,
              color = NA) +
  geom_line(size = 1)+
  labs(y = 'within_pair - across_pair',
       x = 'within trial timepoint') +
  scale_colour_manual(values=cbPalette, name = "ROIs")+
  guides(fill = FALSE) + 
  theme_classic(20) +
  theme(legend.position="bottom") + 
  annotate("text", x=3, y=0.066, label= "same", size=5)+ 
  annotate("text", x=12, y=0.066, label= "overlapping", size=5)+ 
  annotate("text", x=22, y=0.066, label= "non-overlapping", size=5)
```


```{r Talk figures 2, eval=FALSE, include=FALSE}

tmp$roi = factor(tmp$roi,
                  levels = c('ca23dg-body', 'ca23dg',
                             'ca1-body', 'ca1',
                             'hippocampus', 'ppa',
                             'angular_gyrus', 'evc'))

tmp2 = tmp %>% group_by(sub, segment, valid, roi) %>% 
  summarise(wp_ap_m = mean(wp_ap),
            wp_ap_se = sd(wp_ap)/sqrt(n())
            )  %>% 
  filter(roi %in% c('ca23dg-body', 'ppa', 'evc') &
         valid == 'valid')

tmp2 %>% group_by(segment, valid, roi) %>% 
  summarise(m = mean(wp_ap_m),
            se = sd(wp_ap_m)/sqrt(n()),
            n = n()
            ) %>%
  ggplot(aes(x = segment, y = m, fill = roi)) +
  geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
  geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.2) +
  geom_point(data = tmp2, aes(x = segment, y = wp_ap_m, color = roi, group = roi), 
             size = 2,
              position=position_jitterdodge(
                jitter.height = 0,
                jitter.width = 0.75,
                dodge.width = 0.75)) + 
  labs(y = 'within_pair - across_pair')+ 
  theme_classic(20)+
  theme(legend.position="bottom",
        legend.title = element_blank(),
        strip.background = element_blank()) + 
  facet_wrap(~roi, ncol = 3, scales = 'free_y') 
  
```
