---
title: "poster"
author: "Wanjia Guo"
date: '2022-10-30'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
cbPalette <- c("#CC79A7","#0072B2","#009E73","#E69F00","#56B4E9","#F0E442","#999999","#D55E00")

all_sub_df = all_sub_df_clean %>% mutate(wp_ap = within_pair - across_pair,
         segment = factor(segment, levels = c('same', 'overlapping', 'non-overlapping'))) %>% 
  filter(valid != 'invalid-invalid')

df = all_sub_df
```

```{r}

tmp = df %>% mutate(wp_ap = within_pair - across_pair,
       segment = factor(segment, levels = c('same', 'overlapping', 'non-overlapping'))) 

levels(tmp$segment) <- list(same = "same", 
                             similar = "overlapping",
                             different = "non-overlapping")



tmp$roi =  factor(tmp$roi,
              levels = c('ca23dg-body', 'ca23dg',
                         
                         'ca1-body', 'ca1','ppa',
                         'hippocampus', 
                         'angular_gyrus', 'evc'))

tmp_sub = tmp %>% group_by(segment, valid, within_trial_TR, roi) %>%
  summarise(wp_ap_m = mean(wp_ap),
            wp_ap_se = sd(wp_ap)/sqrt(n()),
            wi_wp_m = mean(wi_wp),
            wi_wp_se = sd(wi_wp)/sqrt(n()),
            )

tmp_sub$roi =  factor(tmp_sub$roi,
                         levels = c('ca23dg-body', 'ca23dg',
                                    
                                    'ca1-body', 'ca1','ppa',
                                    'hippocampus', 
                                    'angular_gyrus', 'evc'))

tmp2 = tmp %>% group_by(sub, segment, valid, roi) %>% 
    summarise(wp_ap_m = mean(wp_ap),
              wp_ap_se = sd(wp_ap)/sqrt(n())
              )

levels(tmp2$roi) <- list(ca23dg = "ca23dg-body", 
                             ca1 = "ca1-body",
                            ppa = "ppa",
                             evc = "evc")

tmp2 %>% group_by(segment, valid, roi) %>% 
    summarise(m = mean(wp_ap_m),
              se = sd(wp_ap_m)/sqrt(n()),
              n = n()
              ) %>% 
  filter(valid == 'valid-valid') %>% 
    ggplot(aes(x = segment, y = m, fill = roi)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
    geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
    geom_point(data = tmp2 %>% filter(valid == 'valid-valid'),
               aes(x = segment, y = wp_ap_m, color = roi, group = roi), 
                position=position_jitterdodge(
                  jitter.width = 0.2,
                  dodge.width = 0.75)) + 
    geom_blank(data = tmp2 %>% filter(valid == 'valid-valid'), aes(y=-wp_ap_m))+
    labs(y = 'Similarity Scores')+ 
    facet_wrap(~roi, nrow = 1, scales = 'free_y')+
  theme_classic(20)+
    theme(legend.position = 'none',
          legend.title = element_blank(),
          strip.background = element_blank()
          )+
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)

tmp2 %>% group_by(segment, valid, roi) %>% 
    summarise(m = mean(wp_ap_m),
              se = sd(wp_ap_m)/sqrt(n()),
              n = n()
              ) %>% 
  filter(valid == 'valid-invalid') %>% 
    ggplot(aes(x = segment, y = m, fill = roi)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
    geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
    geom_point(data = tmp2 %>% filter(valid == 'valid-invalid'),
               aes(x = segment, y = wp_ap_m, color = roi, group = roi), 
                position=position_jitterdodge(
                  jitter.width = 0.2,
                  dodge.width = 0.75)) + 
    geom_blank(data = tmp2 %>% filter(valid == 'valid-invalid'), aes(y=-wp_ap_m))+
    labs(y = 'Similarity Scores')+
  theme_classic(20)+
    facet_wrap(~roi, nrow = 1, scales = 'free_y')+
    theme(legend.position = 'none',
          legend.title = element_blank(),
          strip.background = element_blank())+
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)
```

# early - late

```{r}

levels(fig_df$segment) <- list(same = "same", 
                             overlap = "overlapping",
                             different = "non-overlapping")


fig_df %>% 
      group_by(segment, roi, valid, type, phase) %>% 
      summarise(m = mean(mean),
                se = sd(mean)/sqrt(n()),
                n = n()
                ) %>% 
      ggplot(aes(x = segment, y = m, fill = phase)) +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.9), width=0.5) +
      geom_point(data = fig_df, aes(x = segment, y = mean, color = phase, group = phase), 
                  position=position_jitterdodge(
                    jitter.width = 0.2,
                    dodge.width = 0.9)) + 
      labs(y = 'PSA')+ 
      theme( legend.position='bottom',
             legend.title = element_blank()) + 
    facet_wrap(valid~roi,scales = 'free_y', ncol = 4)+
  colorblindr::scale_fill_OkabeIto()+ 
  colorblindr::scale_color_OkabeIto()
```


# Valid and invalid

```{r}

all_sub_df_both = all_sub_df_clean %>% mutate(wp_ap = within_pair - across_pair,
         segment = factor(segment, levels = c('same', 'overlapping', 'non-overlapping'))) %>% 
  filter(valid != 'invalid-invalid')

all_sub_plot = all_sub_df_both %>% 
  group_by(segment, within_trial_TR, roi, sub, valid) %>%
  nest() %>% 
  broadcast(calculate_mean) %>% 
  select(-data) %>% 
  unnest(cols = output) 

tmp = all_sub_plot %>% mutate(wp_ap = within_pair - across_pair) 

tmp$roi =  factor(tmp$roi,
              levels = c('ca23dg-body', 'ca23dg',
                         'ppa',
                         'ca1-body', 'ca1',
                         'hippocampus', 
                         'angular_gyrus', 'evc'))

t = tmp %>% filter(roi == 'ca23dg-body') %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$wp_ap)$p.value) %>% 
  unnest(output) %>%
  mutate(sig = ifelse(output <= 0.05, TRUE, FALSE))

timepoint4 = t %>% filter(within_trial_TR == 4) %>% unnest(data)

t.test(timepoint4 %>% filter(valid == 'valid-valid') %>% .$wp_ap,
       timepoint4 %>% filter(valid == 'valid-invalid') %>% .$wp_ap,
       paired = TRUE)

tmp_sub = tmp %>% group_by(segment, valid, within_trial_TR, roi) %>%
  summarise(wp_ap_m = mean(wp_ap),
            wp_ap_se = sd(wp_ap)/sqrt(n())
            )

tmp_sub$roi =  factor(tmp_sub$roi,
                         levels = c('ca23dg-body', 'ca23dg',
                                    'ppa',
                                    'ca1-body', 'ca1',
                                    'hippocampus', 
                                    'angular_gyrus', 'evc'))

tmp_sub$valid = factor(tmp_sub$valid, 
                          levels = c("valid-valid",
                                     "valid-invalid"))
levels(tmp_sub$valid) <- list(valid = "valid-valid", 
                           invalid = "valid-invalid")
  
p1 = tmp_sub %>% 
    filter(roi == 'ca23dg-body') %>% 
    ggplot(aes(x = within_trial_TR, y = wp_ap_m, color = valid)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = wp_ap_m-wp_ap_se, 
                    ymax = wp_ap_m+wp_ap_se,
                    fill = valid),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'Similarity Scores',
         x = element_blank()) + 
    theme(legend.position = 'top',
          legend.title = element_blank(),
          strip.background = element_blank())+
    facet_wrap(~valid, nrow = 2)+
    scale_x_continuous(breaks = seq(2, 24, by = 2))+
    coord_cartesian(xlim = c(1,24))+
  colorblindr::scale_fill_OkabeIto(order = 5:6)+ 
  colorblindr::scale_color_OkabeIto(order = 5:6)

p1

p2 = postscan2_batch %>%
    filter(correct == 1) %>%
    ggplot(aes(x = ceiling_tp)) +
    geom_histogram(binwidth = 1) +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    scale_x_continuous(breaks = seq(2,24,2), limit = c(1,24))+
    xlab("Within Trial Timepoint (seconds)")+
    ylab('Post Test\nCorrect Count') +
    coord_cartesian(xlim = c(1,24))

p2

library(cowplot)
plot_grid(p1, p2, ncol=1, align='v', rel_heights = c(2/3, 1/3))

```


# Separating overlapping route

```{r}
sep_over = all_sub_df_clean %>% 
  mutate(wp_ap = within_pair - across_pair,
  segment = ifelse(segment != 'overlapping', segment,
                   ifelse(within_trial_TR <= 12, 
                          'early_overlap',
                          'late_overlap'))
) %>% filter(valid != 'invalid-invalid') %>% 
  mutate(valid = factor(valid, levels = c('valid-valid', 'valid-invalid')))

tmp_sub = sep_over %>% group_by(segment, valid, within_trial_TR, roi) %>%
  summarise(wp_ap_m = mean(wp_ap),
            wp_ap_se = sd(wp_ap)/sqrt(n())
            )

tmp_sub$roi =  factor(tmp_sub$roi,
              levels = c('ca23dg-body','ca1-body','ppa','evc'))

p1 = tmp_sub %>% 
  filter(roi != 'evc' & roi != 'ca1-body' & roi != 'ppa') %>% 
  ggplot(aes(x = within_trial_TR, y = wp_ap_m, color = roi)) +
  geom_hline(yintercept = 0, linetype="longdash") +
  geom_vline(xintercept=6, linetype="longdash") +
  geom_vline(xintercept=18, linetype="longdash") +
  geom_ribbon(aes(ymin = wp_ap_m-wp_ap_se, 
                  ymax = wp_ap_m+wp_ap_se,
                  fill = roi),
              alpha = 0.2,
              color = NA) +
  geom_line(size = 1)+
  labs(y = 'PSA',
       x = 'within trial timepoint') + 
  theme(legend.position = 'none',
        legend.title = element_blank(),
        strip.background = element_blank())+ 
  facet_wrap(~valid, nrow = 2)+
scale_fill_manual(values = cbPalette)+ 
scale_color_manual(values = cbPalette)

p1

tmp2 = sep_over %>% group_by(sub, segment, valid, roi) %>% 
    summarise(wp_ap_m = mean(wp_ap),
              wp_ap_se = sd(wp_ap)/sqrt(n())
              ) %>% 
  mutate(segment = factor(segment,
                          levels = c('same', 'early_overlap', 'late_overlap', 'non-overlapping')),
         roi = factor(roi,
                      levels = c('ca23dg-body','ca1-body','ppa','evc')))

levels(tmp2$segment) <- list(same = "same", 
                             early = "early_overlap",
                            late = "late_overlap",
                             different = "non-overlapping")
levels(tmp2$roi) <- list(ca23dg = "ca23dg-body", 
                             ca1 = "ca1-body",
                            ppa = "ppa",
                             evc = "evc")

valid = tmp2 %>% filter(valid == 'valid-valid')
  
tmp3 = valid %>% group_by(segment, valid, roi) %>% 
    summarise(m = mean(wp_ap_m),
              se = sd(wp_ap_m)/sqrt(n()),
              n = n()
              ) %>% 
  mutate(segment = factor(segment))


ggplot(data = tmp3,
       aes(x = segment, y = m, fill = roi)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
    geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
    geom_point(data = valid, 
               aes(x = segment, y = wp_ap_m, color = roi, group = roi), 
                position=position_jitterdodge(
                  jitter.width = 0.2,
                  dodge.width = 0.75)) + 
    labs(y = 'PSA')+ 
    facet_wrap(~roi, nrow = 1, scales = 'free_y')+
    theme(legend.position = 'none',
          legend.title = element_blank(),
          strip.background = element_blank())+
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)
  
for (seg in unique(valid$segment)){
  print(seg)
  print(t.test(valid %>% filter(roi == 'ca23dg' & segment == seg) %>% .$wp_ap_m))
}

t.test(valid %>% filter(roi == 'ca23dg' & segment == 'early') %>% .$wp_ap_m,
valid %>% filter(roi == 'ca23dg' & segment == 'late') %>% .$wp_ap_m,
paired = TRUE
)
```

```{r}
invalid = tmp2 %>% filter(valid == 'valid-invalid')


tmp4 = invalid %>% group_by(segment, valid, roi) %>% 
    summarise(m = mean(wp_ap_m),
              se = sd(wp_ap_m)/sqrt(n()),
              n = n()
              ) %>% 
  mutate(segment = factor(segment))


ggplot(data = tmp4,
       aes(x = segment, y = m, fill = roi)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
    geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
    geom_point(data = invalid, 
               aes(x = segment, y = wp_ap_m, color = roi, group = roi), 
                position=position_jitterdodge(
                  jitter.width = 0.2,
                  dodge.width = 0.75)) + 
    labs(y = 'PSA')+ 
    facet_wrap(~roi, nrow = 1, scales = 'free_y')+
    theme(legend.position = 'none',
          legend.title = element_blank(),
          strip.background = element_blank())+
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)
  
for (seg in unique(invalid$segment)){
  print(seg)
  print(t.test(invalid %>% filter(roi == 'ca23dg' & segment == seg) %>% .$wp_ap_m))
}

t.test(invalid %>% filter(roi == 'ca23dg' & segment == 'early') %>% .$wp_ap_m,
invalid %>% filter(roi == 'ca23dg' & segment == 'late') %>% .$wp_ap_m,
paired = TRUE)
```

