---
title: "Timeseries analysis - early vs. late learning"
author: "Wanjia Guo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

library(tidyverse)
library(fs)
library(ggplot2)
library(ez)
library(gt)
theme_set(theme_classic(12))

library(ezPurrr)

cbPalette <- c("#CC79A7","#009E73","#0072B2","#E69F00","#56B4E9","#F0E442","#999999","#D55E00")
#pink, green, blue, yellow
```

```{r reading in data, include=FALSE}
converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub_x))
}

sub_dir = dir_ls(here::here("./csv_files/python_summary"))

rois_names = c('ca23dg-body', 'ca1-body', 
               'evc', 'ppa')

files <- map(sub_dir, dir_ls, glob = '*/*rolling3_*summary_with_rounds.csv') %>% unlist()

rolling <- map_dfr(files, converting_read)
  
```

```{r}
sub_p1 = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(sub != '13' & sub != '23') %>% 
  pivot_wider(names_from = type, values_from = cor) %>% 
  mutate(wp_ap = within - across) %>% 
  select(-c(across, within, same))%>% 
  mutate('time' = ifelse((round_x <= 5 & round_y <= 5), 'early',
                         ifelse((round_x > 5 & round_y > 5), 'late',
                                'others'))) %>%
  filter(time != 'others')

p1 = sub_p1 %>% 
  group_by(valid, within_trial_TR, roi, time) %>%
  summarise(mean = mean(wp_ap),
            se = sd(wp_ap)/sqrt(n()),
            n = n())

p1$roi = factor(p1$roi, levels = c('ca23dg-body', 'ppa', 'ca1-body', 'evc'))
p1$valid = factor(p1$valid, levels = c('valid-valid', 'valid-invalid', 'invalid-invalid'))
```

## n = `r length(unique(sub_p1$sub))`

```{r}

figure = p1 %>% 
    ggplot(aes(x = within_trial_TR, y = mean, color = time)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = mean-se, 
                    ymax = mean+se,
                    fill = time),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'within_pair - across_pair',
         x = 'within trial timepoint') + 
    theme(legend.position = 'bottom',
          legend.title = element_blank(),
          strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)+
  facet_wrap(roi~valid,
             scales = 'free_y',
             nrow = 4)

print(figure)

```

```{r}
ca23dg = sub_p1 %>% filter(roi == 'ca23dg-body')

t = ca23dg %>% 
  select(-c(round_x, round_y, sub_x)) %>% 
  group_by(sub, valid, within_trial_TR, time) %>% 
  summarise(m = mean(wp_ap)) %>% 
  pivot_wider(names_from = time, values_from = m) %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$early, .$late, paired = TRUE)$p.value) %>% 
  unnest(output) %>%
  mutate(paired = output) %>% 
  select(-c(data, output))

a = ca23dg %>% 
  select(-c(round_x, round_y, sub_x)) %>% 
  group_by(sub, valid, within_trial_TR, time) %>% 
  summarise(m = mean(wp_ap)) %>% 
  pivot_wider(names_from = time, values_from = m) %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$`early`)$p.value) %>%
  unnest(output) %>%
  mutate(early = output) %>% 
  broadcast(~t.test(.$`late`)$p.value) %>%
  unnest(output) %>%
  mutate(late = output) %>% 
  select(-c(data, output)) 

t = inner_join(a, t, by = c("within_trial_TR", "valid"))

t %>% ungroup() %>% gt(
    groupname_col = "valid") %>%
  row_group_order(groups = c("valid-valid", "valid-invalid")) %>%
  tab_header(title = "Timepoint p-values for ca23dg-body") %>%
  fmt_number(
    columns = c(early, late, paired),
    decimals = 3
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `early`,
      rows = `early` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `late`,
      rows = `late` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `paired`,
      rows = `paired` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `paired`,
      rows = `paired` < 0.05
    )
  )
```
