---
title: "Timeseries analysis"
author: "Wanjia Guo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

library(tidyverse)
library(fs)
library(ggplot2)
library(ez)
library(gt)
theme_set(theme_classic(12))

library(ezPurrr)

cbPalette <- c("#CC79A7","#009E73","#0072B2","#E69F00","#56B4E9","#F0E442","#999999","#D55E00")
#pink, green, blue, yellow
```

```{r reading in data, include=FALSE}
converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub_x))
}

sub_dir = dir_ls(here::here("./csv_files/python_summary"))

rois_names = c('ca23dg-body', 'ca1-body', 
               'evc', 'ppa')

#files <- map(sub_dir, dir_ls, glob = '*/*rolling3_*summary.csv') %>% unlist()
files <- map(sub_dir, dir_ls, glob = '*/*norolling_*summary.csv') %>% unlist()

rolling <- map_dfr(files, converting_read)
  
```


```{r}
bad = c('13', '20', '23', '24', '27')

rolling = rolling %>% 
  filter(!(sub %in% bad))
```

```{r}
sub_p1 = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  pivot_wider(names_from = type, values_from = cor) %>% 
  mutate(wp_ap = within - across) %>% 
  select(-c(across, within, same))

p1 = sub_p1 %>% 
  group_by(valid, within_trial_TR, roi) %>%
  summarise(mean = mean(wp_ap),
            se = sd(wp_ap)/sqrt(n()),
            n = n())

p1$roi = factor(p1$roi, levels = c('ca23dg-body', 'ppa', 'ca1-body', 'evc', 'ca23dg', 'ca1'))
p1$valid = factor(p1$valid, levels = c('valid-valid', 'valid-invalid', 'invalid-invalid'))
```

## n = `r length(unique(sub_p1$sub))`

```{r}

figure = p1 %>% 
    ggplot(aes(x = within_trial_TR, y = mean, color = valid)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = mean-se, 
                    ymax = mean+se,
                    fill = valid),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'within_pair - across_pair',
         x = 'within trial timepoint') + 
    theme(legend.position = 'bottom',
          legend.title = element_blank(),
          strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)+
  facet_wrap(~roi,
             scales = 'free_y',
             nrow = 4)

print(figure)

```



```{r}
ca23dg = sub_p1 %>% filter(roi == 'ca23dg-body')

t = ca23dg %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$wp_ap)$p.value) %>% 
  unnest(output) %>%
  #mutate(sig = ifelse(output <= 0.05, TRUE, FALSE)) %>% 
  select(-data) %>% 
  pivot_wider(names_from = valid,
              values_from = output)

a = ca23dg %>% 
  pivot_wider(names_from = valid,
              values_from = wp_ap) %>% 
  group_by(within_trial_TR) %>% 
  nest() %>% 
  broadcast(~t.test(.$`valid-valid`, .$`valid-invalid`, 
                    paired = TRUE)$p.value) %>%
  unnest(output) %>%
  mutate(paired = output) %>% 
  select(-c(data, output)) 

t = inner_join(t, a, by = c("within_trial_TR"))

t %>% ungroup() %>% gt() %>% 
  tab_header(title = "Timepoint p-values for ca23dg-body") %>%
  fmt_number(
    #columns = c(`valid-invalid`, `valid-valid`, paired,`invalid-invalid`),
    columns = c(`valid-invalid`, `valid-valid`, paired),
    decimals = 3
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-invalid`,
      rows = `valid-invalid` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-valid`,
      rows = `valid-valid` < 0.05
    )
  )%>%
#  tab_style(
#    style = list(
#      cell_fill(color = "lightcyan"),
#      cell_text(weight = "bold",
#                color = "red")
#      ),
#    locations = cells_body(
#      columns = `invalid-invalid`,
#      rows = `invalid-invalid` < 0.05
#    )
#  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `paired`,
      rows = `paired` < 0.05
    )
  )
```


```{r}
ca1 = sub_p1 %>% filter(roi == 'ca1-body')

t = ca1 %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$wp_ap)$p.value) %>% 
  unnest(output) %>%
  #mutate(sig = ifelse(output <= 0.05, TRUE, FALSE)) %>% 
  select(-data) %>% 
  pivot_wider(names_from = valid,
              values_from = output)

a = ca1 %>% 
  pivot_wider(names_from = valid,
              values_from = wp_ap) %>% 
  group_by(within_trial_TR) %>% 
  nest() %>% 
  broadcast(~t.test(.$`valid-valid`, .$`valid-invalid`, 
                    paired = TRUE)$p.value) %>%
  unnest(output) %>%
  mutate(paired = output) %>% 
  select(-c(data, output)) 

t = inner_join(t, a, by = c("within_trial_TR"))

t %>% ungroup() %>% gt() %>% 
  tab_header(title = "Timepoint p-values for ca1-body") %>%
  fmt_number(
    #columns = c(`valid-invalid`, `valid-valid`, paired,`invalid-invalid`),
    columns = c(`valid-invalid`, `valid-valid`, paired),
    decimals = 3
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-invalid`,
      rows = `valid-invalid` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-valid`,
      rows = `valid-valid` < 0.05
    )
  )%>%
#  tab_style(
#    style = list(
#      cell_fill(color = "lightcyan"),
#      cell_text(weight = "bold",
#                color = "red")
#      ),
#    locations = cells_body(
#      columns = `invalid-invalid`,
#      rows = `invalid-invalid` < 0.05
#    )
#  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `paired`,
      rows = `paired` < 0.05
    )
  )
```



```{r}
ppa = sub_p1 %>% filter(roi == 'ppa')

t = ppa %>% 
  group_by(within_trial_TR, valid) %>% 
  nest() %>% 
  broadcast(~t.test(.$wp_ap)$p.value) %>% 
  unnest(output) %>%
  #mutate(sig = ifelse(output <= 0.05, TRUE, FALSE)) %>% 
  select(-data) %>% 
  pivot_wider(names_from = valid,
              values_from = output)

a = ppa %>% 
  pivot_wider(names_from = valid,
              values_from = wp_ap) %>% 
  group_by(within_trial_TR) %>% 
  nest() %>% 
  broadcast(~t.test(.$`valid-valid`, .$`valid-invalid`, 
                    paired = TRUE)$p.value) %>%
  unnest(output) %>%
  mutate(paired = output) %>% 
  select(-c(data, output)) 

t = inner_join(t, a, by = c("within_trial_TR"))

t %>% ungroup() %>% gt() %>% 
  tab_header(title = "Timepoint p-values for ppa") %>%
  fmt_number(
    #columns = c(`valid-invalid`, `valid-valid`, paired,`invalid-invalid`),
    columns = c(`valid-invalid`, `valid-valid`, paired),
    decimals = 3
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-invalid`,
      rows = `valid-invalid` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `valid-valid`,
      rows = `valid-valid` < 0.05
    )
  )%>%
  tab_style(
    style = list(
      cell_fill(color = "lightcyan"),
      cell_text(weight = "bold",
                color = "red")
      ),
    locations = cells_body(
      columns = `paired`,
      rows = `paired` < 0.05
    )
  )
```

```{r poster, eval=FALSE, include=FALSE}
sub_dir = dir_ls(here::here("./csv_files/behavior"))
postscan2_behav <- map(sub_dir, dir_ls, glob = '*postscan2*_behav*.csv') %>% unlist()
converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub))
}
postscan2_batch <- map_dfr(postscan2_behav, converting_read)

bad = c('20', '24', '27')
postscan2_batch <- postscan2_batch %>% 
  filter(sub != '14' & sub != '30' & sub != '34') %>% 
  filter(!(sub %in% bad))

postscan2_batch = postscan2_batch %>% 
  mutate(
  correct = ifelse(!is.na(post_first_resp_obj) & post_first_resp_obj == destination, 1, 0))
postscan2_batch = postscan2_batch %>% mutate(tp = npic * 0.24, floor_tp = floor(tp), ceiling_tp = ceiling(tp))

f2 = postscan2_batch %>%
  filter(correct == 1) %>%
  ggplot(aes(x = ceiling_tp)) +
  geom_histogram(binwidth = 1) +
  geom_vline(xintercept=6) +
  geom_vline(xintercept=18) +
  scale_x_continuous(breaks = seq(0,24,2), limit = c(1,24))+
  xlab("Within Trial Timepoint (seconds)")+
  ylab("Count")

f1 = p1 %>% 
    filter(roi == 'ca23dg-body') %>% 
    ggplot(aes(x = within_trial_TR, y = mean, color = valid)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = mean-se, 
                    ymax = mean+se,
                    fill = valid),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'Similarity Scores',
         x = element_blank()) + 
    theme(legend.position = 'top',
          legend.title = element_blank(),
          strip.background = element_blank())+ 
  scale_x_continuous(breaks = seq(0,24,2), limit = c(1,24))+
  colorblindr::scale_fill_OkabeIto(order = 5:6)+ 
  colorblindr::scale_color_OkabeIto(order = 5:6)

cowplot::plot_grid(f1, f2, ncol=1, align='v', rel_heights = c(2/3, 1/3))
```

