---
title: "Timeseries analysis - early vs. late learning"
author: "Wanjia Guo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

library(tidyverse)
library(fs)
library(ggplot2)
library(ez)
library(gt)
theme_set(theme_classic(12))

library(ezPurrr)

cbPalette <- c("#CC79A7","#009E73","#0072B2","#E69F00","#56B4E9","#F0E442","#999999","#D55E00")
#pink, green, blue, yellow
```

```{r reading in data, include=FALSE}
converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub_x))
}

sub_dir = dir_ls(here::here("./csv_files/python_summary"))

rois_names = c('ca23dg-body', 'ca1-body', 
               'evc', 'ppa')

files <- map(sub_dir, dir_ls, glob = '*/*rolling3_*summary_with_pair.csv') %>% unlist()
rolling <- map_dfr(files, converting_read)

files <- map(sub_dir, dir_ls, glob = '*/*norolling_*summary_with_pair.csv') %>% unlist()
norolling <- map_dfr(files, converting_read)
```

```{r}
sub_across = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(sub != '13' & sub != '23' & type == 'across') %>% 
  group_by(sub, roi, within_trial_TR, valid) %>% 
    summarise(across = mean(cor), n = n())
  
  
sub_within = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(sub != '13' & sub != '23' & type == 'within') %>% 
  mutate(pair = pair_x, within = cor) %>% 
  select(-c(pair_x, pair_y, sub_x, cor))

sub_p1 = left_join(sub_within, sub_across) %>% 
  mutate(wp_ap = within - across) %>% 
  select(-c(type, within, across, n))

p1 = sub_p1 %>% 
  group_by(valid, within_trial_TR, roi, pair) %>%
  summarise(mean = mean(wp_ap),
            se = sd(wp_ap)/sqrt(n()),
            n = n())

p1$roi = factor(p1$roi, levels = c('ca23dg-body', 'ppa', 'ca1-body', 'evc'))
p1$valid = factor(p1$valid, levels = c('valid-valid', 'valid-invalid', 'invalid-invalid'))
```

## n = `r length(unique(sub_p1$sub))`

```{r}

figure = p1 %>% 
    ggplot(aes(x = within_trial_TR, y = mean, color = valid)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = mean-se, 
                    ymax = mean+se,
                    fill = valid),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'within_pair - across_pair',
         x = 'within trial timepoint') + 
    theme(legend.position = 'bottom',
          legend.title = element_blank(),
          strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)+
  facet_wrap(roi~pair,
             scales = 'free_y',
             nrow = 4)

print(figure)

```

```{r}
f1 = p1 %>% 
    filter(roi == 'ca23dg-body') %>% 
    ggplot(aes(x = within_trial_TR, y = mean)) +
    geom_hline(yintercept = 0, linetype="longdash") +
    geom_vline(xintercept=6, linetype="longdash") +
    geom_vline(xintercept=18, linetype="longdash") +
    geom_ribbon(aes(ymin = mean-se, 
                    ymax = mean+se),
                alpha = 0.2,
                color = NA) +
    geom_line(size = 1)+
    labs(y = 'within_pair - across_pair',
         x = 'within trial timepoint') + 
    theme(legend.position = 'bottom',
          legend.title = element_blank(),
          strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)+
  facet_wrap(valid~pair,
             scales = 'free_y',
             ncol = 4)
```



```{r include=FALSE}
converting_read <- function(curr_path){
  print(curr_path)
  read_csv(curr_path) %>% mutate(sub = as.character(sub))
}
sub_dir = dir_ls(here::here("./csv_files/behavior"))
postscan2_behav <- map(sub_dir, dir_ls, glob = '*postscan2*_behav*.csv') %>% unlist()
postscan2_batch <- map_dfr(postscan2_behav, converting_read)

postscan2_batch <- postscan2_batch %>% 
  filter(sub != '14' & sub != '30' & sub != '34' & sub != '13' & sub != '23')

postscan2_batch = postscan2_batch %>% 
  mutate(
  correct = ifelse(!is.na(post_first_resp_obj) & post_first_resp_obj == destination, 1, 0))

```


```{r}
f2 = postscan2_batch %>%
  filter(correct == 1) %>%
  mutate(tp = npic * 0.24, ceiling_tp = ceiling(tp)) %>% 
  mutate(route = factor(route, levels = c('pair1_east','pair2_north','pair3_west','pair4_south')),
         destination = factor(destination, levels = c('bench','bikerack','shrub','pergola','pole','window','entrance','map'))) %>%
  ggplot(aes(x = ceiling_tp, fill = sub)) +
  geom_histogram() +
  geom_vline(xintercept=6) +
  geom_vline(xintercept=18) +
  labs(title = 'Picture index for correct trials')+
  facet_wrap(~route, ncol = 4, scales = "free_y")+
  theme(strip.background = element_blank(),
        legend.position = 'none')
```


```{r}
library(cowplot)

plot_grid(f1, f2, ncol=1, align='v', rel_heights = c(2/3, 1/3))

```

## No Rolling

six seconds around avg response time (e.g. response at 7.8s, including 5-10 seconds data)

```{r}
tmp = postscan2_batch %>% 
  filter(correct == 1) %>%
  group_by(route, sub) %>% 
  nest() %>% 
  broadcast(~mean(.$npic))
  select(-data) %>% 
  mutate(
    output = as.numeric(output),
    tp = output * 0.24, 
    ceiling_tp = ceiling(tp) + 2,
    floor_tp = floor(tp) - 2,
    sub = as.numeric(sub))
```

```{r include=FALSE}
sub_across = norolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(sub != '13' & sub != '23' & type == 'across') %>% 
  group_by(sub, roi, within_trial_TR, valid) %>% 
    summarise(across = mean(cor), n = n())
  
sub_within = norolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(sub != '13' & sub != '23' & type == 'within') %>% 
  mutate(pair = pair_x, within = cor) %>% 
  select(-c(pair_x, pair_y, sub_x, cor))

sub_p1 = left_join(sub_within, sub_across) %>% 
  mutate(wp_ap = within - across) %>% 
  select(-c(type, within, across, n))

f3_sub =
left_join(sub_p1 %>% mutate(sub = as.numeric(sub)), 
          tmp, by = c("sub" = "sub", "pair" = "route")) %>% 
  filter(within_trial_TR <= ceiling_tp & within_trial_TR >= floor_tp) %>% 
  group_by(roi, valid, sub) %>% 
  summarise(cor = mean(wp_ap), n = n())

f3_norolling = f3_sub %>% 
  group_by(roi, valid) %>% 
  summarise(m = mean(cor), 
            se = sd(cor)/sqrt(n()),
            n = n())
```


```{r}
ggplot(f3_norolling, aes(x = valid, y = m)) +
      geom_hline(yintercept = 0, linetype="longdash") +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
      labs(y = 'within_pair - across_pair')+ 
      facet_wrap(~roi, ncol = 2, scales = 'free_y')+
      theme(legend.position = 'top',
            legend.title = element_blank(),
            strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)

 t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-valid'))$cor)
t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-invalid'))$cor)

t.test((f3_sub %>% filter(roi == 'ca1-body' & valid == 'valid-invalid'))$cor)

```

3 seconds prior to response (if the response time is 7.8, 5-7 seconds data are included)

```{r include=FALSE}
tmp2 = postscan2_batch %>% 
  filter(correct == 1) %>%
  group_by(route, sub) %>% 
  nest() %>% 
  broadcast(~mean(.$npic)) %>% 
  select(-data) %>% 
  mutate(
    output = as.numeric(output),
    tp = output * 0.24, 
    ceiling_tp = floor(tp),
    floor_tp = floor(tp) - 2,
    sub = as.numeric(sub))

f3_sub =
left_join(sub_p1 %>% mutate(sub = as.numeric(sub)), 
          tmp2, by = c("sub" = "sub", "pair" = "route")) %>%
  filter(within_trial_TR <= ceiling_tp & within_trial_TR >= floor_tp) %>% 
  group_by(roi, valid, sub) %>% 
  summarise(cor = mean(wp_ap), n = n())
f3_norolling = f3_sub %>% 
  group_by(roi, valid) %>% 
  summarise(m = mean(cor), 
            se = sd(cor)/sqrt(n()),
            n = n())
```


```{r}
ggplot(f3_norolling, aes(x = valid, y = m)) +
      geom_hline(yintercept = 0, linetype="longdash") +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
      labs(y = 'within_pair - across_pair')+ 
      facet_wrap(~roi, ncol = 2, scales = 'free_y')+
      theme(legend.position = 'top',
            legend.title = element_blank(),
            strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)

t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-valid'))$cor)
t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-invalid'))$cor)

t.test((f3_sub %>% filter(roi == 'ca1-body' & valid == 'valid-invalid'))$cor)

```

3 seconds post response (if the response time is 7.8, 8-10 seconds data are included)

```{r include=FALSE}
tmp3 = postscan2_batch %>% 
  filter(correct == 1) %>%
  group_by(route, sub) %>% 
  nest() %>% 
  broadcast(~mean(.$npic)) %>% 
  select(-data) %>% 
  mutate(
    output = as.numeric(output),
    tp = output * 0.24, 
    ceiling_tp = ceiling(tp) + 2,
    floor_tp = floor(tp) + 1,
    sub = as.numeric(sub))

f3_sub =
left_join(sub_p1 %>% mutate(sub = as.numeric(sub)), 
          tmp3, by = c("sub" = "sub", "pair" = "route")) %>%
  filter(within_trial_TR <= ceiling_tp & within_trial_TR >= floor_tp) %>% 
  group_by(roi, valid, sub) %>% 
  summarise(cor = mean(wp_ap), n = n())
f3_norolling = f3_sub %>% 
  group_by(roi, valid) %>% 
  summarise(m = mean(cor), 
            se = sd(cor)/sqrt(n()),
            n = n())
```


```{r}
ggplot(f3_norolling, aes(x = valid, y = m)) +
      geom_hline(yintercept = 0, linetype="longdash") +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
      labs(y = 'within_pair - across_pair')+ 
      facet_wrap(~roi, ncol = 2, scales = 'free_y')+
      theme(legend.position = 'top',
            legend.title = element_blank(),
            strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)

t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-valid'))$cor)
t.test((f3_sub %>% filter(roi == 'ca23dg-body' & valid == 'valid-invalid'))$cor)

t.test((f3_sub %>% filter(roi == 'ca1-body' & valid == 'valid-invalid'))$cor)

```