---
title: "paper-draft2: withtin item analysis"
author: "Wanjia Guo"
date: '2023-09-25'
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

# Set up

```{r setup, include=FALSE}
source("./utils.R")

#postscan2_batch = loading_postscan2_df()

rolling1 = loading_rolling_trial_df() %>% select(-sub_x)

rolling2 =  rolling1
rolling2$round_x = rolling1$round_y
rolling2$round_y = rolling1$round_x
rolling2$trial_x = rolling1$trial_y
rolling2$trial_y = rolling1$trial_x

rolling = rbind(rolling1, rolling2)

unique(rolling$segment)

rolling_sub = rolling %>% 
  filter(round_x <= 5 | round_y <=5) %>% 
  group_by(type, segment, round_x, trial_x, roi, sub) %>% 
  summarise(m = mean(cor))

rolling_type = rolling_sub %>% 
  pivot_wider(names_from = 'type', values_from = m) %>% 
  mutate(m = across-within) %>% 
  select(-c(across, within)) %>% 
  filter(roi %in% c('ca23dg-body', 'ca1-body')) %>% 
  pivot_wider(names_from = c(segment, roi), values_from = m)


correlation <- function(df){
  mat = cor(df, method='spearman')
  mat %>% rstatix::cor_gather() %>% filter(var1 != var2)
}

corr = rolling_type %>% group_by(sub) %>% 
  select(-c(round_x, trial_x)) %>% 
  nest() %>% 
  broadcast(~correlation(.))%>%
  unnest(output) %>% 
  select(-data) %>% 
  group_by(var1, var2) %>% 
  summarise(cor = mean(cor), .groups = 'rowwise')

corr$var1 = factor(corr$var1, levels = c("same_ca23dg-body", "same_ca1-body",
                                         "early-similar_ca23dg-body","early-similar_ca1-body",
                                         "late-similar_ca23dg-body","late-similar_ca1-body",
                                         "different_ca1-body","different_ca23dg-body"))
  
corr$var2 = factor(corr$var2, levels = c("same_ca23dg-body", "same_ca1-body",
                                         "early-similar_ca23dg-body","early-similar_ca1-body",
                                         "late-similar_ca23dg-body","late-similar_ca1-body",
                                         "different_ca1-body","different_ca23dg-body"))


ggplot(corr %>% filter(str_detect(var1, 'ca23dg')) %>% filter(str_detect(var2, 'ca1')), 
       aes(x=var1, y=var2, fill=cor)) + 
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-0.15,0.15), space = "Lab", 
   name="Spearman\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()+
  labs(x = element_blank(),
       y = element_blank())+
  geom_text(aes(x=var1, y=var2, 
                label = round(cor,3)),
            color = "black",
            size = 3)


ggplot(corr %>% filter(str_detect(var1, 'ca23dg')) %>% filter(str_detect(var2, 'ca23dg')), 
       aes(x=var1, y=var2, fill=cor)) + 
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-0.15,0.15), space = "Lab", 
   name="Spearman\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()+
  labs(x = element_blank(),
       y = element_blank()) +
  geom_text(aes(x=var1, y=var2, 
                label = round(cor,3)),
            color = "black",
            size = 3)

ggplot(corr %>% filter(str_detect(var1, 'ca1')) %>% filter(str_detect(var2, 'ca1')), 
       aes(x=var1, y=var2, fill=cor)) + 
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-0.15,0.15), space = "Lab", 
   name="Spearman\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()+
  labs(x = element_blank(),
       y = element_blank()) +
  geom_text(aes(x=var1, y=var2, 
                label = round(cor,3)),
            color = "black",
            size = 3)
  
  
  summarize(same_ca23dg_early = cor(`same_ca23dg-body`, `early-similar_ca23dg-body`, method='spearman'),
            same_ca1_early = cor(`same_ca23dg-body`,`early-similar_ca1-body`, method='spearman'),
            same_ca23dg_late = cor(`same_ca23dg-body`, `late-similar_ca23dg-body`, method='spearman'),
            same_ca1_late = cor(`same_ca23dg-body`,`late-similar_ca1-body`, method='spearman'),
            early_ca23dg_late = cor(`early-similar_ca23dg-body`, `late-similar_ca23dg-body`, method='spearman'),
            early_ca1_late = cor(`early-similar_ca23dg-body`,`late-similar_ca1-body`, method='spearman'))

mean(corr$same_ca23dg_early)
mean(corr$same_ca1_early)
mean(corr$same_ca23dg_late)
mean(corr$same_ca1_late)
mean(corr$early_ca23dg_late)
mean(corr$early_ca1_late)

t.test(corr$same_ca23dg_early)
t.test(corr$same_ca1_early)
t.test(corr$same_ca23dg_late)
t.test(corr$same_ca1_late)
t.test(corr$early_ca23dg_late)
t.test(corr$early_ca1_late)
```


```{r}
sub_p2 = rolling_sub %>% 
  group_by(valid, segment, roi, sub, type) %>% 
  summarise(mean = mean(m),
            se = sd(m)/sqrt(n()),
            n = n())

p2 = sub_p2 %>% 
  group_by(valid, segment, roi, type) %>%
  summarise(m = mean(mean),
            se = sd(mean)/sqrt(n()),
            n = n())

p2$segment = factor(p2$segment, levels = c('same', 'early-similar', 'late-similar', 'different'))
p2$roi = factor(p2$roi, levels = c('ca23dg-body', 'ppa', 'ca1-body', 'evc'))
p2$valid = factor(p2$valid, levels = c('valid-valid', 'valid-invalid', 'invalid-invalid'))
p2$type = factor(p2$type, levels = c('same', 'within', 'across'))

ggplot(p2, aes(x = segment, y = m, fill = type)) +
      geom_hline(yintercept = 0, linetype="longdash") +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.85), width=0.5) +
      #geom_point(data = sub_p1, aes(x = segment, y = m, color = roi, group = roi), 
      #            position=position_jitterdodge(
      #              jitter.width = 0.2,
      #              dodge.width = 0.75)) + 
      labs(y = 'within_pair - across_pair')+ 
      facet_wrap(valid~roi, ncol = 2, scales = 'free_y')+
      theme(legend.position = 'bottom',
            legend.title = element_blank(),
            strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)
```

# Pre- and Post- MoI

```{r}
postscan2_batch_correct = postscan2_batch %>% 
  filter(correct == 1) %>%
  mutate(tp = npic * 0.24,
         tp_int = round(tp))

postscan_summary = postscan2_batch_correct %>% 
  group_by(route, sub) %>% 
  summarize(m = mean(tp),
            max = max(tp),
            min = min(tp),
            median = median(round(tp)),
            range = max - min,
            n = n())

tmp = postscan2_batch_correct %>% 
  mutate(tp = round(tp)) %>% 
  group_by(route, sub) %>% 
  nest() %>% 
  broadcast(~max(Modes(.$tp))) %>% 
  mutate(mode = as.numeric(output)) %>% 
  select(-c(data, output))

sub_across = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(type == 'across') %>% 
  group_by(sub, roi, within_trial_TR, valid) %>% 
    summarise(across = mean(cor))
  
sub_within = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(type == 'within') %>% 
  mutate(pair = pair_x, within = cor) %>% 
  select(-c(pair_x, pair_y, cor)) %>% 
  group_by(valid, within_trial_TR, roi, sub, pair) %>% 
  summarise(within = mean(within))

sub_same = rolling %>% 
  filter(valid != 'invalid-invalid') %>% 
  filter(type == 'same') %>% 
  mutate(pair = pair_x, same = cor) %>% 
  select(-c(pair_x, pair_y, cor)) %>% 
  group_by(valid, within_trial_TR, roi, sub, pair) %>% 
  summarise(same = mean(same))

sub_together1 = left_join(sub_within, sub_across,
                          by = c("valid", "within_trial_TR", "roi", "sub")) %>%
  mutate(cor = within - across) %>% 
  select(-c(within, across)) %>% 
  mutate(type = 'wp_ap')

sub_together2 = left_join(sub_same, sub_across,
                          by = c("valid", "within_trial_TR", "roi", "sub")) %>%
  mutate(cor = same - across) %>% 
  select(-c(same, across)) %>% 
  mutate(type = 'wi_ap')

sub_together = rbind(sub_together1, sub_together2)

sub_p3 =
left_join(sub_together %>% mutate(sub = as.numeric(sub)), 
          tmp %>% mutate(sub = as.numeric(sub)), 
          by = c("sub" = "sub", "pair" = "route")) %>%
  mutate(segment = ifelse(within_trial_TR <= mode, 'pre',
                          ifelse(within_trial_TR > mode, 'post', 'MoI'))) %>% 
  filter(segment != 'MoI') %>%
  group_by(roi, valid, sub, segment, type) %>% 
  summarise(cor = mean(cor), n = n())

p3 = sub_p3 %>% 
  group_by(roi, valid, segment, type) %>% 
  summarise(m = mean(cor), 
            se = sd(cor)/sqrt(n()),
            n = n())
```

```{r}
p3$segment = factor(p3$segment,levels = c('pre', 'post'))
p3$roi = factor(p3$roi, levels = c('ca23dg-body', 'ppa', 'ca1-body', 'evc'))
p3$valid = factor(p3$valid, levels = c('valid-valid', 'valid-invalid'))
p3$type = factor(p3$type, levels = c('wi_ap', 'wp_ap'))


ggplot(p3, aes(x = segment, y = m, fill = type)) +
      geom_hline(yintercept = 0, linetype="longdash") +
      geom_bar(stat = 'identity', alpha = 0.5, position = position_dodge()) + 
      geom_errorbar(aes(ymin = m-se, ymax = m+se), position = position_dodge(width = 0.8), width=0.5) +
      labs(y = 'Similarity differences')+ 
      facet_wrap(valid~roi, ncol = 2, scales = 'free_y')+
      theme(legend.position = 'bottom',
            legend.title = element_blank(),
            strip.background = element_blank())+ 
  scale_fill_manual(values = cbPalette)+ 
  scale_color_manual(values = cbPalette)
```
